name: Frontend tests - Cypress
on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         ref: ${{ github.event.pull_request.head.sha }}
      - name: start server/client and run cypress
        uses: cypress-io/github-action@v4
        env: 
          MONGO_URI: ${{secrets.MONGO_URI}}
          TEST_MONGO_URI: ${{secrets.TEST_MONGO_URI}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}  
        with:
          start: yarn start 
          project: client
          config-file: cypress.config.js
