 # This is a basic workflow to help you get started with Actions

name: Backend Tests - Jest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
         ref: ${{ github.event.pull_request.head.sha }}
      - name: Install modules
        run: yarn
      - name: Run tests
        env: 
          MONGO_URI: ${{secrets.MONGO_URI}}
          TEST_MONGO_URI: ${{secrets.TEST_MONGO_URI}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
        run: yarn test:server
